### ISSUE TITLE
Got Segmentation Fault when calling estimate_alpha_knn

### ISSUE THREAD

**Issue by ntuLC** [pymatting/pymatting#15] opened 2020-04-22 10:21 UTC
Got this error both on macOS 10.14 and Ubuntu 16.04

When installing the package I used `--ignore-installed llvmlite` flag for pip because I got 
`Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`. I am not sure if this is relevant.

```
pytest
============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.7.4, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /Users/user/pymatting-master
plugins: arraydiff-0.3, remotedata-0.3.2, doctestplus-0.4.0, openfiles-0.4.0
collected 11 items                                                                                                                                                               

tests/test_boxfilter.py .                                                                                                                                                  [  9%]
tests/test_cg.py .                                                                                                                                                         [ 18%]
tests/test_estimate_alpha.py F                                                                                                                                             [ 27%]
tests/test_foreground.py .                                                                                                                                                 [ 36%]
tests/test_ichol.py .                                                                                                                                                      [ 45%]
tests/test_kdtree.py Fatal Python error: Segmentation fault

Current thread 0x00000001086d7dc0 (most recent call first):
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pymatting/util/kdtree.py", line 280 in __init__
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pymatting/util/kdtree.py", line 347 in knn
  File "/Users/user/pymatting-master/tests/test_kdtree.py", line 20 in run_kdtree
  File "/Users/user/pymatting-master/tests/test_kdtree.py", line 46 in test_kdtree
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/python.py", line 170 in pytest_pyfunc_call
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/python.py", line 1423 in runtest
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 125 in pytest_runtest_call
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 201 in <lambda>
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 229 in from_call
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 201 in call_runtest_hook
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 176 in call_and_report
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 95 in runtestprotocol
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 80 in pytest_runtest_protocol
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/main.py", line 256 in pytest_runtestloop
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/main.py", line 235 in _main
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/main.py", line 191 in wrap_session
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/main.py", line 228 in pytest_cmdline_main
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 90 in main
  File "/Users/user/opt/anaconda3/bin/pytest", line 11 in <module>
[1]    99661 segmentation fault  pytest
```

**Comment by 99991** [comment] 2020-04-22 10:29
This is probably an issue between `numba` and `llvmlite`. Does installing `llvmlite` as described in the README of the `llvmlite` repository in section ["Pre-built binaries"](https://github.com/numba/llvmlite#pre-built-binaries) work?

```bash
conda install --channel=numba llvmlite
```

**Comment by ntuLC** [comment] 2020-04-22 10:54
> This is probably an issue between `numba` and `llvmlite`. Does installing `llvmlite` as described in the README of the `llvmlite` repository in section ["Pre-built binaries"](https://github.com/numba/llvmlite#pre-built-binaries) work?
> 
> ```shell
> conda install --channel=numba llvmlite
> ```

Thanks for your quick reply!

It says the package is already installed... I then updated the numba and llvmlite but unfortunately that still does not help.

**Comment by 99991** [comment] 2020-04-22 11:24
The best idea is probably to look at the test that failed and simplify it until we can identify the line which causes the error.

Below is a stand-alone version of the test. Try running it with and without line 5 with the `@njit` annotation. If it works without njit, the bug is probably with `numba` or `llvmlite`.

If that should be the case, try decreasing the value `n_data` and `k` so the test runs faster and keep checking with and without `@njit` to ensure that it still fails. Next, try deleting random lines from the `_make_tree` function until you are reasonably sure which line is causing the segmentation fault.

Also print the library versions to ensure that they are reasonably up-to-date. For reference, mine are:
```
System: uname_result(system='Linux', node='computer', release='5.3.0-46-generic', version='#38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020', machine='x86_64', processor='x86_64')
llvmlite version: 0.31.0
numba version: 0.48.0
numpy version: 1.18.1
```

```Python3
import numpy as np
import llvmlite
import numba
import platform
from numba import njit

print("System:", platform.uname())
print("llvmlite version:", llvmlite.__version__)
print("numba version:", numba.__version__)
print("numpy version:", np.__version__)

# If this should crash, try without this line
@njit("i8(i8[:], i8[:], i8[:], i8[:], i8[:], f4[:, :, :], f4[:], f4[:, :], i8[:], i8)")
def _make_tree(
    i0_inds,
    i1_inds,
    less_inds,
    more_inds,
    split_dims,
    bounds,
    split_values,
    points,
    indices,
    min_leaf_size,
):
    dimension = points.shape[1]
    # Expect log2(len(points) / min_leaf_size) depth, 1000 should be plenty
    stack = np.empty(1000, np.int64)
    stack_size = 0
    n_nodes = 0
    # min_leaf_size <= leaf_node_size < max_leaf_size
    max_leaf_size = 2 * min_leaf_size

    # Push i0, i1, i_node
    stack[stack_size] = 0
    stack_size += 1
    stack[stack_size] = points.shape[0]
    stack_size += 1
    stack[stack_size] = n_nodes
    n_nodes += 1
    stack_size += 1

    # While there are more tree nodes to process recursively
    while stack_size > 0:
        stack_size -= 1
        i_node = stack[stack_size]
        stack_size -= 1
        i1 = stack[stack_size]
        stack_size -= 1
        i0 = stack[stack_size]

        lo = bounds[i_node, 0]
        hi = bounds[i_node, 1]

        for d in range(dimension):
            lo[d] = points[i0, d]
            hi[d] = points[i0, d]

        # Find lower and upper bounds of points for each dimension
        for i in range(i0 + 1, i1):
            for d in range(dimension):
                lo[d] = min(lo[d], points[i, d])
                hi[d] = max(hi[d], points[i, d])

        # Done if node is small
        if i1 - i0 <= max_leaf_size:
            i0_inds[i_node] = i0
            i1_inds[i_node] = i1
            less_inds[i_node] = -1
            more_inds[i_node] = -1
            split_dims[i_node] = -1
            split_values[i_node] = 0.0
        else:
            # Split on largest dimension
            lengths = hi - lo
            split_dim = np.argmax(lengths)
            split_value = lo[split_dim] + 0.5 * lengths[split_dim]

            # Partition i0:i1 range into points where points[i, split_dim] < split_value
            i = i0
            j = i1 - 1

            while i < j:
                while i < j and points[i, split_dim] < split_value:
                    i += 1
                while i < j and points[j, split_dim] >= split_value:
                    j -= 1

                # Swap points
                if i < j:
                    for d in range(dimension):
                        temp = points[i, d]
                        points[i, d] = points[j, d]
                        points[j, d] = temp

                    temp_i_node = indices[i]
                    indices[i] = indices[j]
                    indices[j] = temp_i_node

            if points[i, split_dim] < split_value:
                i += 1

            i_split = i

            # Now it holds that:
            # for i in range(i0, i_split): assert(points[i, split_dim] < split_value)
            # for i in range(i_split, i1): assert(points[i, split_dim] >= split_value)

            # Ensure that each node has at least min_leaf_size children
            i_split = max(i0 + min_leaf_size, min(i1 - min_leaf_size, i_split))

            less = n_nodes
            n_nodes += 1
            more = n_nodes
            n_nodes += 1

            # push i0, i_split, less
            stack[stack_size] = i0
            stack_size += 1
            stack[stack_size] = i_split
            stack_size += 1
            stack[stack_size] = less
            stack_size += 1

            # push i_split, i1, more
            stack[stack_size] = i_split
            stack_size += 1
            stack[stack_size] = i1
            stack_size += 1
            stack[stack_size] = more
            stack_size += 1

            i0_inds[i_node] = i0
            i1_inds[i_node] = i1
            less_inds[i_node] = less
            more_inds[i_node] = more
            split_dims[i_node] = split_dim
            split_values[i_node] = split_value

    return n_nodes

def main():
    k = 20
    n_data = 100_000
    n_query = n_data
    dimension = 5

    data_points = np.random.rand(n_data, dimension).astype(np.float32)
    min_leaf_size = 8

    n_data, dimension = data_points.shape

    max_nodes = 2 * ((n_data + min_leaf_size - 1) // min_leaf_size)

    i0_inds = np.empty(max_nodes, np.int64)
    i1_inds = np.empty(max_nodes, np.int64)
    less_inds = np.empty(max_nodes, np.int64)
    more_inds = np.empty(max_nodes, np.int64)
    split_dims = np.empty(max_nodes, np.int64)
    bounds = np.empty((max_nodes, 2, dimension), np.float32)
    split_values = np.empty(max_nodes, np.float32)
    shuffled_data_points = data_points.copy()
    shuffled_indices = np.arange(n_data).astype(np.int64)

    _make_tree(
        i0_inds,
        i1_inds,
        less_inds,
        more_inds,
        split_dims,
        bounds,
        split_values,
        shuffled_data_points,
        shuffled_indices,
        min_leaf_size,
    )

main()
```

**Comment by ntuLC** [comment] 2020-04-22 12:18
> The best idea is probably to look at the test that failed and simplify it until we can identify the line which causes the error.
> 
> Below is a stand-alone version of the test. Try running it with and without line 5 with the `@njit` annotation. If it works without njit, the bug is probably with `numba` or `llvmlite`.
> 
> If that should be the case, try decreasing the value `n_data` and `k` so the test runs faster and keep checking with and without `@njit` to ensure that it still fails. Next, try deleting random lines from the `_make_tree` function until you are reasonably sure which line is causing the segmentation fault.
> 
> Also print the library versions to ensure that they are reasonably up-to-date. For reference, mine are:
> 
> ```
> System: uname_result(system='Linux', node='computer', release='5.3.0-46-generic', version='#38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020', machine='x86_64', processor='x86_64')
> llvmlite version: 0.31.0
> numba version: 0.48.0
> numpy version: 1.18.1
> ```
> 
> ```python
> import numpy as np
> import llvmlite
> import numba
> import platform
> from numba import njit
> 
> print("System:", platform.uname())
> print("llvmlite version:", llvmlite.__version__)
> print("numba version:", numba.__version__)
> print("numpy version:", np.__version__)
> 
> # If this should crash, try without this line
> @njit("i8(i8[:], i8[:], i8[:], i8[:], i8[:], f4[:, :, :], f4[:], f4[:, :], i8[:], i8)")
> def _make_tree(
>     i0_inds,
>     i1_inds,
>     less_inds,
>     more_inds,
>     split_dims,
>     bounds,
>     split_values,
>     points,
>     indices,
>     min_leaf_size,
> ):
>     dimension = points.shape[1]
>     # Expect log2(len(points) / min_leaf_size) depth, 1000 should be plenty
>     stack = np.empty(1000, np.int64)
>     stack_size = 0
>     n_nodes = 0
>     # min_leaf_size <= leaf_node_size < max_leaf_size
>     max_leaf_size = 2 * min_leaf_size
> 
>     # Push i0, i1, i_node
>     stack[stack_size] = 0
>     stack_size += 1
>     stack[stack_size] = points.shape[0]
>     stack_size += 1
>     stack[stack_size] = n_nodes
>     n_nodes += 1
>     stack_size += 1
> 
>     # While there are more tree nodes to process recursively
>     while stack_size > 0:
>         stack_size -= 1
>         i_node = stack[stack_size]
>         stack_size -= 1
>         i1 = stack[stack_size]
>         stack_size -= 1
>         i0 = stack[stack_size]
> 
>         lo = bounds[i_node, 0]
>         hi = bounds[i_node, 1]
> 
>         for d in range(dimension):
>             lo[d] = points[i0, d]
>             hi[d] = points[i0, d]
> 
>         # Find lower and upper bounds of points for each dimension
>         for i in range(i0 + 1, i1):
>             for d in range(dimension):
>                 lo[d] = min(lo[d], points[i, d])
>                 hi[d] = max(hi[d], points[i, d])
> 
>         # Done if node is small
>         if i1 - i0 <= max_leaf_size:
>             i0_inds[i_node] = i0
>             i1_inds[i_node] = i1
>             less_inds[i_node] = -1
>             more_inds[i_node] = -1
>             split_dims[i_node] = -1
>             split_values[i_node] = 0.0
>         else:
>             # Split on largest dimension
>             lengths = hi - lo
>             split_dim = np.argmax(lengths)
>             split_value = lo[split_dim] + 0.5 * lengths[split_dim]
> 
>             # Partition i0:i1 range into points where points[i, split_dim] < split_value
>             i = i0
>             j = i1 - 1
> 
>             while i < j:
>                 while i < j and points[i, split_dim] < split_value:
>                     i += 1
>                 while i < j and points[j, split_dim] >= split_value:
>                     j -= 1
> 
>                 # Swap points
>                 if i < j:
>                     for d in range(dimension):
>                         temp = points[i, d]
>                         points[i, d] = points[j, d]
>                         points[j, d] = temp
> 
>                     temp_i_node = indices[i]
>                     indices[i] = indices[j]
>                     indices[j] = temp_i_node
> 
>             if points[i, split_dim] < split_value:
>                 i += 1
> 
>             i_split = i
> 
>             # Now it holds that:
>             # for i in range(i0, i_split): assert(points[i, split_dim] < split_value)
>             # for i in range(i_split, i1): assert(points[i, split_dim] >= split_value)
> 
>             # Ensure that each node has at least min_leaf_size children
>             i_split = max(i0 + min_leaf_size, min(i1 - min_leaf_size, i_split))
> 
>             less = n_nodes
>             n_nodes += 1
>             more = n_nodes
>             n_nodes += 1
> 
>             # push i0, i_split, less
>             stack[stack_size] = i0
>             stack_size += 1
>             stack[stack_size] = i_split
>             stack_size += 1
>             stack[stack_size] = less
>             stack_size += 1
> 
>             # push i_split, i1, more
>             stack[stack_size] = i_split
>             stack_size += 1
>             stack[stack_size] = i1
>             stack_size += 1
>             stack[stack_size] = more
>             stack_size += 1
> 
>             i0_inds[i_node] = i0
>             i1_inds[i_node] = i1
>             less_inds[i_node] = less
>             more_inds[i_node] = more
>             split_dims[i_node] = split_dim
>             split_values[i_node] = split_value
> 
>     return n_nodes
> 
> def main():
>     k = 20
>     n_data = 100_000
>     n_query = n_data
>     dimension = 5
> 
>     data_points = np.random.rand(n_data, dimension).astype(np.float32)
>     min_leaf_size = 8
> 
>     n_data, dimension = data_points.shape
> 
>     max_nodes = 2 * ((n_data + min_leaf_size - 1) // min_leaf_size)
> 
>     i0_inds = np.empty(max_nodes, np.int64)
>     i1_inds = np.empty(max_nodes, np.int64)
>     less_inds = np.empty(max_nodes, np.int64)
>     more_inds = np.empty(max_nodes, np.int64)
>     split_dims = np.empty(max_nodes, np.int64)
>     bounds = np.empty((max_nodes, 2, dimension), np.float32)
>     split_values = np.empty(max_nodes, np.float32)
>     shuffled_data_points = data_points.copy()
>     shuffled_indices = np.arange(n_data).astype(np.int64)
> 
>     _make_tree(
>         i0_inds,
>         i1_inds,
>         less_inds,
>         more_inds,
>         split_dims,
>         bounds,
>         split_values,
>         shuffled_data_points,
>         shuffled_indices,
>         min_leaf_size,
>     )
> 
> main()
> ```

Thanks for your reply! Yes the problem should with `numba`. The code runs well without `@jit` line.
And I found the code also runs without crashing by commenting line 126-131
```
            stack[stack_size] = i_split
            stack_size += 1
            stack[stack_size] = i1
            stack_size += 1
            stack[stack_size] = more
            stack_size += 1
```
Uncommenting any of these lines will add the probability of crashing. 

Sometimes get this:

```
python(25563,0x106803dc0) malloc: Incorrect checksum for freed object 0x7facca789f18: probably modified after being freed.
```

**Comment by 99991** [comment] 2020-04-22 12:26
Ok, in this case the issue can be forwarded to the numba issue tracker: https://github.com/numba/numba/issues

I think it is probably best if you open the issue there because I can't reproduce locally.

You can link back to this issue, so Github will reference it automatically.

**Comment by 99991** [comment] 2020-04-23 16:25
We will work around this issue for now by disabling version `0.49.0` of numba. Should presumably be fixed in the future version `0.49.1`.

**Comment by stuartarchibald** [comment] 2020-04-24 09:17
@99991 is https://github.com/numba/numba/issues/5618 related to this? Whilst it is evidently a problem, I cannot see in the reproducer above a place where that transform would actually take place. It also seems to segfault with the fix (https://github.com/stuartarchibald/numba/commit/2f6309d6c4cc10ad67b2f3cc6cb7f1a6fcbd66fb) in place.

**Comment by 99991** [comment] 2020-04-24 09:39
@stuartarchibald I simplified the code a lot to get the minimal code in https://github.com/numba/numba/issues/5618 so it is quite possible that there are other bugs in numba which are triggered by the original code.

**Comment by stuartarchibald** [comment] 2020-04-24 13:28
Thanks for reducing this @99991, think I've got to the bottom of it here: https://github.com/numba/numba/issues/5623#issuecomment-618970315 will patch for Numba 0.49.1.

**Comment by 99991** [comment] 2020-10-29 09:41
This issue should be fixed with newer numba versions.

**Closed by 99991** 2020-10-29 09:41 UTC
